import { motion } from "framer-motion";
import { PenTool, Target, Search, LifeBuoy } from "lucide-react";
import { Reveal } from "./motion";
const standards = [
  { icon: PenTool, title: "Designed with craft", desc: "We make you the best-looking product in your industry — not a template. Expect to wow customers and make competitors jealous, while still converting." },
  { icon: Target, title: "Built to convert", desc: "Every page is structured around turning visitors into qualified, ready-to-buy leads — with forms, automations and tracking wired in from the start." },
  { icon: Search, title: "Found in search", desc: "We architect each build around the keywords that matter to you, so you launch with a solid SEO foundation instead of an invisible site." },
  { icon: LifeBuoy, title: "Supported end-to-end", desc: "You'll never worry about your systems again. We handle updates, security and monitoring — and you have a real team to call when you need one." },
];
export default function FourReasons() { return <section className="bg-[#F6F7FB] py-20 lg:py-24"><div className="mx-auto max-w-7xl px-6"><Reveal className="text-center max-w-2xl mx-auto mb-14"><span className="text-xs font-bold uppercase tracking-[0.18em] text-[#6D5DF6]">The Sentinels standard</span><h2 className="mt-4 font-display font-extrabold text-[#0B1226] text-3xl lg:text-4xl tracking-tight">Four things you can count on, every project</h2></Reveal><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-5">{standards.map((s,i)=><motion.div key={s.title} initial={{opacity:0,y:24}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{duration:.45,delay:i*.08}} className="rounded-2xl bg-white border border-slate-200/80 p-7 hover:border-[#6D5DF6]/40 hover:-translate-y-1 transition-all"><div className="w-12 h-12 rounded-xl bg-[#0B1226] flex items-center justify-center mb-5"><s.icon className="text-[#2DD4BF]" size={24}/></div><span className="font-mono text-xs text-[#0B1226]/30">0{i+1}</span><h3 className="font-display font-bold text-[#0B1226] text-lg mt-2">{s.title}</h3><p className="mt-2.5 text-sm text-[#0B1226]/60 leading-relaxed">{s.desc}</p></motion.div>)}</div></div></section>; }